// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-7iDWigQotBEtzEutGfLO7i8NrgWFgU',
    appId: '1:985831449098:web:e07d033de7c8fa940975f3',
    messagingSenderId: '985831449098',
    projectId: 'myproject-97812',
    authDomain: 'myproject-97812.firebaseapp.com',
    storageBucket: 'myproject-97812.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3KmlVKnZBdcw-d3fLukUhZd5CbBtpayk',
    appId: '1:985831449098:android:fe3f9085310b09250975f3',
    messagingSenderId: '985831449098',
    projectId: 'myproject-97812',
    storageBucket: 'myproject-97812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDIV9fzjCgZAZ85_J2hVAhw4JQbNIE14',
    appId: '1:985831449098:ios:1ee28a02f55cba1c0975f3',
    messagingSenderId: '985831449098',
    projectId: 'myproject-97812',
    storageBucket: 'myproject-97812.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlDIV9fzjCgZAZ85_J2hVAhw4JQbNIE14',
    appId: '1:985831449098:ios:390039fefce423a30975f3',
    messagingSenderId: '985831449098',
    projectId: 'myproject-97812',
    storageBucket: 'myproject-97812.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
